line_of_credit/config/routes.rb
Rails.application.routes.draw do
  resources :transactions

  root 'transactions#new'

end

line_of_credit/app/models/transaction.rb
class Transaction < ActiveRecord::Base
  validates_presence_of :day_number, :change_amount, :transaction_type
  validates :day_number, numericality: { greater_than: 0, only_integer: true }

  # assume withdraw and payment are made at the begining of the day.
  # principal and interest are calculated at the end of the day.

  def self.principal_on_day(num)
    where("day_number <= #{num}").sum(:change_amount)
  end

  def self.interest_on_day(num, apr_percent)
    adjusted_num = num - num % 30 + 1
    
    apr = apr_percent.to_f / 100
    transactions = where("day_number <= #{adjusted_num}").order(day_number: :desc)
    temp = []
    transactions.each_with_index {|t, i|
      if i == 0
        previous_day_number = adjusted_num
        duration = previous_day_number - t.day_number - 1
      elsif i == transactions.size - 1
        previous_day_number = transactions[i-1].day_number
        duration = previous_day_number - t.day_number + 1
      else
        previous_day_number = transactions[i-1].day_number
        duration = previous_day_number - t.day_number 
      end

      temp << transactions.where("day_number < #{previous_day_number}").sum(:change_amount) * duration
    }

    (apr / 365 * (temp.reduce(:+) || 0)).round(2)
  end

  def self.balance_on_day(num, apr_percent)
    principal_on_day(num) + interest_on_day(num, apr_percent)
  end

  def self.next_closing_day
    if all.size == 0
      30
    else
      ((order(:day_number).last.day_number / 30) + 1) * 30
    end
  end
end

line_of_credit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

line_of_credit/app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

line_of_credit/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  APR_PERCENT = 35
  CREDIT_LIMIT = 5000
  def new
    @transactions = Transaction.all.order(:day_number)
    @transaction = Transaction.new
    @next_closing_day = Transaction.next_closing_day
    @principal = Transaction.principal_on_day(@next_closing_day)
    @interest = Transaction.interest_on_day(@next_closing_day, APR_PERCENT)
  end

  def create
    @transaction = Transaction.new transaction_params
    if transaction_params[:transaction_type] == 'payment'
      @transaction.change_amount = -1 * @transaction.change_amount
    end

    if @transaction.valid? and within_credit_limit?
      @transaction.save!
      flash[:notice] = "New transaction added."
    end

    redirect_to :root

  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy!
    flash[:notice] = "Transaction removed."
    redirect_to :root
  end

  private
  def within_credit_limit?
    if Transaction.all.sum(:change_amount) + @transaction.change_amount <= CREDIT_LIMIT
      true
    else
      flash[:alert] = "Can not exceed credit limit of #{CREDIT_LIMIT}!"
      false
    end
  end
  

  def transaction_params
    params.require(:transaction).permit(:day_number, :transaction_type, :change_amount)
  end
end

line_of_credit/app/helpers/application_helper.rb
module ApplicationHelper
end

line_of_credit/app/helpers/page_helper.rb
module PageHelper
end

line_of_credit/app/helpers/transactions_helper.rb
module TransactionsHelper
end

line_of_credit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>LineOfCredit</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  </head>
  <body>
    <div class="container">
      <% if flash[:alert] %>
        <p class="col-md-6 col-md-offset-3 alert alert-danger"><%= flash[:alert] %></p>
      <% end %>
      <% if flash[:notice] %>
        <p class="col-md-6 col-md-offset-3 alert alert-success"><%= flash[:notice] %></p>
      <% end %>
    <%= yield %>
    </div>

    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

line_of_credit/app/views/transactions/_history.haml
.row
  .col-md-6.col-md-offset-3
    %table.table
      %thead
        %td Day #
        %td Type
        %td Amount
        %td Interest (APR 35%)
        %td 
      %tbody
        - @transactions.each do |t|
          %tr
            %td 
              = t.day_number
            %td 
              = t.transaction_type
            %td 
              = number_to_currency t.change_amount
            %td
              
            %td
              = link_to '', transaction_path(t), method: :delete, class: 'glyphicon glyphicon-remove'
        %tr.info
          %td
            = @next_closing_day
          %td
          %td
            = number_to_currency @principal
          %td
            = number_to_currency @interest
          %td
            Total:&nbsp; 
            = number_to_currency (@principal + @interest)

line_of_credit/app/views/transactions/new.haml
.row
  .col-md-6.col-md-offset-3
    %p Credit line is $5000.00
    .panel.panel-primary
      .panel-heading Add new transaction
      .panel-body
        = simple_form_for @transaction do |f|
          = f.input :transaction_type, collection: ['withdraw', 'payment'], selected: 'withdraw'
          = f.input :day_number, input_html: { min: 1 }
          = f.input :change_amount, label: 'Amount', input_html: { min: 0.01 }
          = f.button :submit, "Submit"

= render 'history'